### ISSUE TITLE
fcm推送报错咋办鸭

### ISSUE THREAD

**Issue by amos2333** [CJieLuo/NotificationPush#7]
备用机_服务端报错下面代码

--------- beginning of main
08-05 19:36:30.063  4592 17974 E error:  : Can't send com.tencent.mm 群聊
08-05 19:40:06.459  4592  4592 E ResourceType: Style contains key with bad entry: 0x0101056c
08-05 19:40:06.465  4592  4592 E ResourceType: Style contains key with bad entry: 0x0101056c
08-05 19:41:56.677  4592  4592 E ResourceType: Style contains key with bad entry: 0x0101056c
08-05 19:41:56.682  4592  4592 E ResourceType: Style contains key with bad entry: 0x0101056c
08-05 19:42:01.949  4592  4592 E ResourceType: Style contains key with bad entry: 0x0101056c
08-05 19:42:01.956  4592  4592 E ResourceType: Style contains key with bad entry: 0x0101056c

主力机_接收端

--------- beginning of main
08-05 18:50:30.892 21158 21158 E otificationpus: Unknown bits set in runtime_flags: 0x40000
08-05 18:50:30.908 21158 21158 E otificationpus: Not starting debugger since process cannot load the jdwp agent.
08-05 18:50:31.092 21158 21209 E Perf    : Fail to get file list com.RichardLuo.notificationpush
08-05 18:50:31.093 21158 21209 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08-05 18:50:31.093 21158 21209 E Perf    : Fail to get file list com.RichardLuo.notificationpush
08-05 18:50:31.093 21158 21209 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08-05 18:50:31.093 21158 21209 E Perf    : Fail to get file list oat
08-05 18:50:31.093 21158 21209 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08-05 18:50:31.157 21158 21215 E ViewContentFactory: NameNotFoundException
08-05 18:50:31.157 21158 21215 E ViewContentFactory: android.content.pm.PackageManager$NameNotFoundException: com.miui.catcherpatch
08-05 18:50:31.157 21158 21215 E ViewContentFactory: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(Unknown Source:16)
08-05 18:50:31.157 21158 21215 E ViewContentFactory: 	at android.app.ApplicationPackageManager.getPackageInfo(Unknown Source:4)
08-05 18:50:31.157 21158 21215 E ViewContentFactory: 	at com.miui.contentcatcher.f.mb(SourceFile:9)
08-05 18:50:31.157 21158 21215 E ViewContentFactory: 	at com.miui.contentcatcher.f.Le(SourceFile:6)
08-05 18:50:31.157 21158 21215 E ViewContentFactory: 	at com.miui.contentcatcher.f.lb(SourceFile:2)
08-05 18:50:31.157 21158 21215 E ViewContentFactory: 	at com.miui.contentcatcher.Interceptor.<init>(SourceFile:29)
08-05 18:50:31.157 21158 21215 E ViewContentFactory: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-05 18:50:31.157 21158 21215 E ViewContentFactory: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
08-05 18:50:31.157 21158 21215 E ViewContentFactory: 	at miui.contentcatcher.InterceptorFactory.createInterceptor(Unknown Source:43)
08-05 18:50:31.157 21158 21215 E ViewContentFactory: 	at miui.contentcatcher.InterceptorProxy$H.handleMessage(Unknown Source:135)
08-05 18:50:31.157 21158 21215 E ViewContentFactory: 	at android.os.Handler.dispatchMessage(Unknown Source:19)
08-05 18:50:31.157 21158 21215 E ViewContentFactory: 	at android.os.Looper.loop(Unknown Source:242)
08-05 18:50:31.157 21158 21215 E ViewContentFactory: 	at android.os.HandlerThread.run(Unknown Source:28)
08-05 18:50:31.157 21158 21215 E ContentCatcher: Interceptor : mViewContentFetcher is NULL
--------- beginning of crash
08-05 18:50:34.318 21158 21322 E AndroidRuntime: FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
08-05 18:50:34.318 21158 21322 E AndroidRuntime: Process: com.RichardLuo.notificationpush, PID: 21158
08-05 18:50:34.318 21158 21322 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
08-05 18:50:34.318 21158 21322 E AndroidRuntime: 	at com.RichardLuo.notificationpush.FCMReceiver.f(:8)
08-05 18:50:34.318 21158 21322 E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessagingService.c(Unknown Source:41)
08-05 18:50:34.318 21158 21322 E AndroidRuntime: 	at z1.m3.run(:152)
08-05 18:50:34.318 21158 21322 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-05 18:50:34.318 21158 21322 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-05 18:50:34.318 21158 21322 E AndroidRuntime: 	at f1.t.run(:12)
08-05 18:50:34.318 21158 21322 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
--------- beginning of system
08-05 18:50:34.327 21158 21322 E MQSEventManagerDelegate: failed to get MQSService.
08-05 18:50:34.327 21158 21322 E MQSEventManagerDelegate: failed to get MQSService.
08-05 18:50:34.355 21158 21210 E cutils-trace: Error opening trace file: No such file or directory (2)
08-05 18:50:38.426 21389 21389 E otificationpus: Unknown bits set in runtime_flags: 0x40000
08-05 18:50:38.430 21389 21389 E otificationpus: Not starting debugger since process cannot load the jdwp agent.
08-05 18:50:38.564 21389 21423 E Perf    : Fail to get file list com.RichardLuo.notificationpush
08-05 18:50:38.564 21389 21423 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08-05 18:50:38.565 21389 21423 E Perf    : Fail to get file list com.RichardLuo.notificationpush
08-05 18:50:38.565 21389 21423 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08-05 18:50:38.565 21389 21423 E Perf    : Fail to get file list oat
08-05 18:50:38.565 21389 21423 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08-05 18:50:38.606 21389 21427 E ViewContentFactory: NameNotFoundException
08-05 18:50:38.606 21389 21427 E ViewContentFactory: android.content.pm.PackageManager$NameNotFoundException: com.miui.catcherpatch
08-05 18:50:38.606 21389 21427 E ViewContentFactory: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(Unknown Source:16)
08-05 18:50:38.606 21389 21427 E ViewContentFactory: 	at android.app.ApplicationPackageManager.getPackageInfo(Unknown Source:4)
08-05 18:50:38.606 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.f.mb(SourceFile:9)
08-05 18:50:38.606 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.f.Le(SourceFile:6)
08-05 18:50:38.606 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.f.lb(SourceFile:2)
08-05 18:50:38.606 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.Interceptor.<init>(SourceFile:29)
08-05 18:50:38.606 21389 21427 E ViewContentFactory: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-05 18:50:38.606 21389 21427 E ViewContentFactory: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
08-05 18:50:38.606 21389 21427 E ViewContentFactory: 	at miui.contentcatcher.InterceptorFactory.createInterceptor(Unknown Source:43)
08-05 18:50:38.606 21389 21427 E ViewContentFactory: 	at miui.contentcatcher.InterceptorProxy$H.handleMessage(Unknown Source:135)
08-05 18:50:38.606 21389 21427 E ViewContentFactory: 	at android.os.Handler.dispatchMessage(Unknown Source:19)
08-05 18:50:38.606 21389 21427 E ViewContentFactory: 	at android.os.Looper.loop(Unknown Source:242)
08-05 18:50:38.606 21389 21427 E ViewContentFactory: 	at android.os.HandlerThread.run(Unknown Source:28)
08-05 18:50:38.606 21389 21427 E ContentCatcher: Interceptor : mViewContentFetcher is NULL
08-05 18:50:47.524 21389 21424 E cutils-trace: Error opening trace file: No such file or directory (2)
08-05 19:36:35.758 21389 21427 E ViewContentFactory: NameNotFoundException
08-05 19:36:35.758 21389 21427 E ViewContentFactory: android.content.pm.PackageManager$NameNotFoundException: com.miui.catcherpatch
08-05 19:36:35.758 21389 21427 E ViewContentFactory: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(Unknown Source:16)
08-05 19:36:35.758 21389 21427 E ViewContentFactory: 	at android.app.ApplicationPackageManager.getPackageInfo(Unknown Source:4)
08-05 19:36:35.758 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.f.mb(SourceFile:9)
08-05 19:36:35.758 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.f.Le(SourceFile:6)
08-05 19:36:35.758 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.f.lb(SourceFile:2)
08-05 19:36:35.758 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.Interceptor.<init>(SourceFile:29)
08-05 19:36:35.758 21389 21427 E ViewContentFactory: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-05 19:36:35.758 21389 21427 E ViewContentFactory: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
08-05 19:36:35.758 21389 21427 E ViewContentFactory: 	at miui.contentcatcher.InterceptorFactory.createInterceptor(Unknown Source:43)
08-05 19:36:35.758 21389 21427 E ViewContentFactory: 	at miui.contentcatcher.InterceptorProxy$H.handleMessage(Unknown Source:135)
08-05 19:36:35.758 21389 21427 E ViewContentFactory: 	at android.os.Handler.dispatchMessage(Unknown Source:19)
08-05 19:36:35.758 21389 21427 E ViewContentFactory: 	at android.os.Looper.loop(Unknown Source:242)
08-05 19:36:35.758 21389 21427 E ViewContentFactory: 	at android.os.HandlerThread.run(Unknown Source:28)
08-05 19:36:35.758 21389 21427 E ContentCatcher: Interceptor : mViewContentFetcher is NULL
08-05 19:39:55.794 21389 21427 E ViewContentFactory: NameNotFoundException
08-05 19:39:55.794 21389 21427 E ViewContentFactory: android.content.pm.PackageManager$NameNotFoundException: com.miui.catcherpatch
08-05 19:39:55.794 21389 21427 E ViewContentFactory: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(Unknown Source:16)
08-05 19:39:55.794 21389 21427 E ViewContentFactory: 	at android.app.ApplicationPackageManager.getPackageInfo(Unknown Source:4)
08-05 19:39:55.794 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.f.mb(SourceFile:9)
08-05 19:39:55.794 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.f.Le(SourceFile:6)
08-05 19:39:55.794 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.f.lb(SourceFile:2)
08-05 19:39:55.794 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.Interceptor.<init>(SourceFile:29)
08-05 19:39:55.794 21389 21427 E ViewContentFactory: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-05 19:39:55.794 21389 21427 E ViewContentFactory: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
08-05 19:39:55.794 21389 21427 E ViewContentFactory: 	at miui.contentcatcher.InterceptorFactory.createInterceptor(Unknown Source:43)
08-05 19:39:55.794 21389 21427 E ViewContentFactory: 	at miui.contentcatcher.InterceptorProxy$H.handleMessage(Unknown Source:135)
08-05 19:39:55.794 21389 21427 E ViewContentFactory: 	at android.os.Handler.dispatchMessage(Unknown Source:19)
08-05 19:39:55.794 21389 21427 E ViewContentFactory: 	at android.os.Looper.loop(Unknown Source:242)
08-05 19:39:55.794 21389 21427 E ViewContentFactory: 	at android.os.HandlerThread.run(Unknown Source:28)
08-05 19:39:55.794 21389 21427 E ContentCatcher: Interceptor : mViewContentFetcher is NULL
08-05 19:40:21.638 21389 21427 E ViewContentFactory: NameNotFoundException
08-05 19:40:21.638 21389 21427 E ViewContentFactory: android.content.pm.PackageManager$NameNotFoundException: com.miui.catcherpatch
08-05 19:40:21.638 21389 21427 E ViewContentFactory: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(Unknown Source:16)
08-05 19:40:21.638 21389 21427 E ViewContentFactory: 	at android.app.ApplicationPackageManager.getPackageInfo(Unknown Source:4)
08-05 19:40:21.638 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.f.mb(SourceFile:9)
08-05 19:40:21.638 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.f.Le(SourceFile:6)
08-05 19:40:21.638 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.f.lb(SourceFile:2)
08-05 19:40:21.638 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.Interceptor.<init>(SourceFile:29)
08-05 19:40:21.638 21389 21427 E ViewContentFactory: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-05 19:40:21.638 21389 21427 E ViewContentFactory: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
08-05 19:40:21.638 21389 21427 E ViewContentFactory: 	at miui.contentcatcher.InterceptorFactory.createInterceptor(Unknown Source:43)
08-05 19:40:21.638 21389 21427 E ViewContentFactory: 	at miui.contentcatcher.InterceptorProxy$H.handleMessage(Unknown Source:135)
08-05 19:40:21.638 21389 21427 E ViewContentFactory: 	at android.os.Handler.dispatchMessage(Unknown Source:19)
08-05 19:40:21.638 21389 21427 E ViewContentFactory: 	at android.os.Looper.loop(Unknown Source:242)
08-05 19:40:21.638 21389 21427 E ViewContentFactory: 	at android.os.HandlerThread.run(Unknown Source:28)
08-05 19:40:21.638 21389 21427 E ContentCatcher: Interceptor : mViewContentFetcher is NULL
08-05 19:46:44.979 21389 21427 E ViewContentFactory: NameNotFoundException
08-05 19:46:44.979 21389 21427 E ViewContentFactory: android.content.pm.PackageManager$NameNotFoundException: com.miui.catcherpatch
08-05 19:46:44.979 21389 21427 E ViewContentFactory: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(Unknown Source:16)
08-05 19:46:44.979 21389 21427 E ViewContentFactory: 	at android.app.ApplicationPackageManager.getPackageInfo(Unknown Source:4)
08-05 19:46:44.979 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.f.mb(SourceFile:9)
08-05 19:46:44.979 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.f.Le(SourceFile:6)
08-05 19:46:44.979 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.f.lb(SourceFile:2)
08-05 19:46:44.979 21389 21427 E ViewContentFactory: 	at com.miui.contentcatcher.Interceptor.<init>(SourceFile:29)
08-05 19:46:44.979 21389 21427 E ViewContentFactory: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-05 19:46:44.979 21389 21427 E ViewContentFactory: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
08-05 19:46:44.979 21389 21427 E ViewContentFactory: 	at miui.contentcatcher.InterceptorFactory.createInterceptor(Unknown Source:43)
08-05 19:46:44.979 21389 21427 E ViewContentFactory: 	at miui.contentcatcher.InterceptorProxy$H.handleMessage(Unknown Source:135)
08-05 19:46:44.979 21389 21427 E ViewContentFactory: 	at android.os.Handler.dispatchMessage(Unknown Source:19)
08-05 19:46:44.979 21389 21427 E ViewContentFactory: 	at android.os.Looper.loop(Unknown Source:242)
08-05 19:46:44.979 21389 21427 E ViewContentFactory: 	at android.os.HandlerThread.run(Unknown Source:28)
08-05 19:46:44.979 21389 21427 E ContentCatcher: Interceptor : mViewContentFetcher is NULL
08-05 19:46:53.033 24096 24096 E otificationpus: Unknown bits set in runtime_flags: 0x40000
08-05 19:46:53.037 24096 24096 E otificationpus: Not starting debugger since process cannot load the jdwp agent.
08-05 19:46:53.147 24096 24128 E Perf    : Fail to get file list com.RichardLuo.notificationpush
08-05 19:46:53.147 24096 24128 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08-05 19:46:53.147 24096 24128 E Perf    : Fail to get file list com.RichardLuo.notificationpush
08-05 19:46:53.147 24096 24128 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08-05 19:46:53.147 24096 24128 E Perf    : Fail to get file list oat
08-05 19:46:53.147 24096 24128 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08-05 19:46:53.192 24096 24134 E ViewContentFactory: NameNotFoundException
08-05 19:46:53.192 24096 24134 E ViewContentFactory: android.content.pm.PackageManager$NameNotFoundException: com.miui.catcherpatch
08-05 19:46:53.192 24096 24134 E ViewContentFactory: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(Unknown Source:16)
08-05 19:46:53.192 24096 24134 E ViewContentFactory: 	at android.app.ApplicationPackageManager.getPackageInfo(Unknown Source:4)
08-05 19:46:53.192 24096 24134 E ViewContentFactory: 	at com.miui.contentcatcher.f.mb(SourceFile:9)
08-05 19:46:53.192 24096 24134 E ViewContentFactory: 	at com.miui.contentcatcher.f.Le(SourceFile:6)
08-05 19:46:53.192 24096 24134 E ViewContentFactory: 	at com.miui.contentcatcher.f.lb(SourceFile:2)
08-05 19:46:53.192 24096 24134 E ViewContentFactory: 	at com.miui.contentcatcher.Interceptor.<init>(SourceFile:29)
08-05 19:46:53.192 24096 24134 E ViewContentFactory: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-05 19:46:53.192 24096 24134 E ViewContentFactory: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
08-05 19:46:53.192 24096 24134 E ViewContentFactory: 	at miui.contentcatcher.InterceptorFactory.createInterceptor(Unknown Source:43)
08-05 19:46:53.192 24096 24134 E ViewContentFactory: 	at miui.contentcatcher.InterceptorProxy$H.handleMessage(Unknown Source:135)
08-05 19:46:53.192 24096 24134 E ViewContentFactory: 	at android.os.Handler.dispatchMessage(Unknown Source:19)
08-05 19:46:53.192 24096 24134 E ViewContentFactory: 	at android.os.Looper.loop(Unknown Source:242)
08-05 19:46:53.192 24096 24134 E ViewContentFactory: 	at android.os.HandlerThread.run(Unknown Source:28)
08-05 19:46:53.192 24096 24134 E ContentCatcher: Interceptor : mViewContentFetcher is NULL

**Comment by RichardLuo0** [comment]
看上去像是miui的一个叫com.miui.contentcatcher的app在拦截我获取打开app的intent，本来的话在原生上点击通知应该是能调起你主力机上的同样的app，但是他miui拦截了的话，那我就删掉这个功能给你打包一份你试试
[app-release.zip](https://github.com/RichardLuo0/NotificationPush/files/9269216/app-release.zip)
